# Generated by Django 4.0.5 on 2023-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_reais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('DESPESA', 'despesa'), ('RECEITA', 'receita')], max_length=10)),
            ],
        ),
    ]
